sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
  - mysql

before_install:
  - docker pull openjdk:8-jdk-alpine

before_script:
  - mysql -u root -e "CREATE DATABASE auth;"
  - mysql -u root -e "CREATE USER 'localroot'@'localhost' IDENTIFIED BY 'localroot';"
  - mysql -u root -e "GRANT ALL ON auth.* TO 'localroot'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"

script:
  - mvn test
  - mvn clean package

after_script:
  - docker-compose up --build