sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
  - mysql

before_install:
  - docker pull openjdk:8-jdk-alpine

script:
  - mvn test
  - mvn clean package

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "springbootdockermodule"
  env: "Springbootdockermodule-env"
  bucket_name: "elasticbeanstalk-us-east-2-300813874739"
  bucket_path: "springbootdockermodule"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY