sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

before_install:
  - docker pull openjdk:8-jdk-alpine

before_script:
  - mysql -e 'create database auth if not exists;'

script:
  - mvn test
  - mvn clean package

after_script:
  - docker-compose up --build