sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
  - mysql

before_install:
  - docker pull openjdk:8-jdk-alpine

script:
  - mvn test
  - mvn clean package

after_script:
  - docker-compose up --build