version: '3'
services:
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./simple
      dockerfile: Dockerfile
    ports:
      - 9001:9000
    volumes:
      - .:/appVolume
