version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'
    volumes:
      - ./nginx:/etc/nginx/app.conf
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./simple
      dockerfile: Dockerfile
    ports:
      - '9001:9000'
    environment:
      - DATABASE_URL=jdbc:mysql://10.149.233.18:3306/auth
      - DATABASE_USER=localroot
      - DATABASE_PASSWORD=localroot
    volumes:
      - .:/appVolume
    depends_on:
      - nginx

