version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./simple
      dockerfile: Dockerfile
    ports:
      - '9001:9000'
    volumes:
      - .:/appVolume
    environment:
      - DATABASE_URL = jdbc:mysql://10.0.75.1:3306/auth
      - DATABASE_USER = localroot
      - DATABASE_PASSWORD = localroot
    depends_on:
      - nginx

